spring.application.name=api-gateway
server.port=8080

# Rutas hacia ms-academico
spring.cloud.gateway.mvc.routes[0].id=ms-academico
spring.cloud.gateway.mvc.routes[0].uri=${ACADEMICO_URL:http://localhost:8081}
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/asignaturas/**,/api/cursos/**,/api/alumnos/**,/api/profesores/**,/api/evaluaciones/**

# Rutas hacia ms-asistencia
spring.cloud.gateway.mvc.routes[1].id=ms-asistencia
spring.cloud.gateway.mvc.routes[1].uri=${ASISTENCIA_URL:http://localhost:8082}
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/asistencias/**,/api/anotaciones/**

# Rutas hacia ms-mensajeria
spring.cloud.gateway.mvc.routes[2].id=ms-mensajeria
spring.cloud.gateway.mvc.routes[2].uri=${MENSAJERIA_URL:http://localhost:8083}
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/mensajes/**
